[JuliaInXL]
git-tree-sha1 = "b8a5c1175aafbc57cda7b3c529718d9fd9ff8f2f"
os = "windows"

    [[JuliaInXL.download]]
    url = "https://juliaprodownloads.blob.core.windows.net/juliapro/juliainxl/juliainxl.tar.gz"
    sha256 = "a533e60a97491515bbda4f881246d00a5af2da2f277bd7d3a29b6ad10768b435"