[JuliaInXL]
git-tree-sha1 = "ed1b754ad4556e2bbda7941d12d10f282a2f135b"
os = "windows"

    [[JuliaInXL.download]]
    url = "https://github.com/JuliaComputing/JuliaInXL.jl/releases/download/v0.0.2/juliainxl.tar.gz"
    sha256 = "a533e60a97491515bbda4f881246d00a5af2da2f277bd7d3a29b6ad10768b435"